### PR TITLE
Sprint2 ls

### PR DESCRIPTION
**Pull request by LukeSandsor**
Hey fellas please review.

### CODE REVIEW

**Review by LukeyReyno — APPROVED** [review]
LGTM. Nice ui changes to the weights page

**Review by brettgowling — APPROVED** [review]
+ Great use of indentation for clarity
+ Variable and function names are clear
+ Even with clear function names, comments above functions or css classes might be helpful

Great stuff, LGTM!

**Comment by LukeyReyno** [comment]
heheha

**Comment by jmarenin** [comment]
Looks good to me, code clarity is strong and styling is good. LGTM

**Review by jmarenin — APPROVED** [review]

**Pull request merged**
