### PR TITLE
User Backend Prototype / Test & BMI Visual Updates

### PR DESCRIPTION
**Pull request by brettgowling**
**Please review my code. All feedback is welcome, so let me know if you have any suggestions or fixes. Thanks!**

This pull request includes a first draft attempt at pulling data from a user entry in the backend and uses it to calculate the BMI bubble number. If proven to work, accessing data specific to a user can be implemented. Additionally, small aesthetic changes were made to the BMI table page.

### CODE REVIEW

**Review by LukeyReyno — APPROVED** [review]
Good schema for users, seems like it will be easy to integrate.
Test cases are good too.
LGTM

**Review by LukeSandsor — APPROVED** [review]
Maybe add a newline to the end of user-services.js when you get a chance.
Other than that, LGTM.

**Comment by jmarenin** [comment]
Besides what Luke Sandsor said about user-services.js, this all looks well done. LGTM

**Review by jmarenin — APPROVED** [review]

**Comment by brettgowling** [comment]
Thanks for the feedback! I've added a newline to the end of user-services.js that will appear in the next pull request.

**Pull request merged**
